[package]
name = "taimi_meta"
authors = [ "kittywitch" ]
description = "GW2 Metadata"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[features]
default = [
  "serde",
  #"mumblelink-nexus",
  "spatial",
]
map-cache = [
  "serde",
  "gzip",
]
nexus = [
  "dep:nexus",
  "arcloader-mumblelink?/nexus",
]
nexus-rtapi = [
  "nexus",
  "nexus/rtapi",
]
mumblelink-arcloader = [
  "taimi_mumblelink",
  "dep:arcloader-mumblelink",
]
mumblelink-nexus = [
  # deprecated, juggling impls for multiple crate versions isn't worth it...
  "taimi_mumblelink",
  "nexus?/mumble",
]
spatial = [
  "dep:bvh",
  "dep:nalgebra",
]
serde = [
  "dep:serde",
  "dep:serde_json",
  "glam/serde",
  "glamour/serde",
  "taimi_hoard/serde",
  #"bvh?/serde",
]
gzip = [
  "dep:async-compression",
  "async-compression/gzip",
]

# internal features
taimi_mumblelink = []

[dependencies]
taimi_hoard = { path = "../../rt/hoard", default-features = true }
anyhow = "1"
async-compression = { version = "0.4.29", optional = true }
bitflags = { workspace = true }
bitvec = { workspace = true }
log = "0.4"
uuid = "1"
md-5 = "0.10"
sha1_smol = { version = "1", features = ["std"], optional = true }
glam = { workspace = true }
glamour = { workspace = true }
mint = { workspace = true }
nalgebra = { workspace = true, optional = true }
bvh = { workspace = true, optional = true }
num-traits = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

arcloader-mumblelink = { git = "https://codeberg.org/TaimiHUD/arcloader", default-features = false, optional = true }
nexus = { workspace = true, optional = true }

[build-dependencies]
compression-codecs = { version = "0.4", features = ["gzip"] }
compression-core = "0.4"
