[package]
name = "taimi_meta"
authors = [ "kittywitch" ]
description = "GW2 Metadata"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[features]
default = [
  "serde",
  "mumblelink-nexus",
]
map-cache = [
  "serde",
  #"gzip", # TODO
]
nexus = [
  "dep:nexus",
]
nexus-rtapi = [
  "nexus",
  "nexus/rtapi",
]
mumblelink-arcloader = [
  "taimi_mumblelink",
  "dep:arcloader-mumblelink",
]
mumblelink-nexus = [
  "taimi_mumblelink",
  "nexus?/mumble",
  "dep:gw2_mumble_nexus",
]
serde = [
  "dep:serde",
  "dep:serde_json",
  "glam/serde",
  "glamour/serde",
]
gzip = [
  "dep:async-compression",
  "async-compression/gzip",
]

# internal features
taimi_mumblelink = []

[dependencies]
anyhow = "1"
async-compression = { version = "0.4.29", optional = true }
bitflags = { workspace = true }
log = "0.4"
tokio = { version = "1", default-features = false }
glam = { workspace = true }
glamour = { workspace = true }
num-traits = { workspace = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

arcloader-mumblelink = { git = "https://github.com/arcnmx/arcloader", default-features = false, optional = true }
# keep version in sync with nexus dependency
gw2_mumble_nexus = { package = "gw2_mumble", git = "https://github.com/zerthox/gw2-mumble-rs", tag = "0.2.4", default-features = false, optional = true }
nexus = { git = "https://github.com/zerthox/nexus-rs", optional = true }

[build-dependencies]
compression-codecs = { version = "0.4", features = ["gzip"] }
compression-core = "0.4"
