[package]
name = "taimi_sim"
authors = [
  "kittywitch",
  "Connicpu",
  "arcnmx"
]
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[example]]
name = "host_win32"
path = "src/main/win32.rs"

[lints]
workspace = true

[features]
default = [
  "windows",
  # TODO: "taimi", # requires crate-type=lib which can't be toggled that easily :<
]
taimi = [
  "dep:taimi_hud",
  "arcloader-mumblelink",
]
windows = [
  "dep:windows",
  "taimi_hud/windows",
  "taimi_d3d/windows",
  "taimi_cover/windows",
]

[dependencies]
taimi_hud = { path = "../..", optional = true, default-features = false, features = [
  "texture-loader", "statistics", "log-filter", "timers", "markers",
  "extension-dyn", "render-rt",
  # TODO: make these optional and actually work when off!
  "space", "timers-space", "markers-edit", "paths",
  "meta-cache", "updates", "extension-nexus",
  # when working on these, but heavy weh :<
  "paths-api", "paths-interact", "paths-lua",
] }
arcffi = { path = "../../rt/ffi", package = "taimi_ffi", default-features = false }
taimi_hosted = { path = "../../rt/hosted", default-features = false }
taimi_hoard = { path = "../../rt/hoard", default-features = false }
taimi_ui = { path = "../../rt/ui", default-features = false }
taimi_log = { path = "../../rt/log", default-features = false }
taimi_d3d = { path = "../../space/d3d", default-features = false, features = ["dx11"] }
taimi_cover = { path = "../../space/cover", default-features = false, features = ["imgui180", "serde"] }
taimi_space = { path = "../../space/pack", default-features = false }
taimi_meta = { path = "../../pathing/meta", default-features = false }
arcloader-mumblelink = { git = "https://codeberg.org/TaimiHUD/arcloader", optional = true, default-features = false }

anyhow = "1"
log = "0.4"
serde_json = "1"
glam = { workspace = true }
glamour = { workspace = true }

include_dir = "0.7"

[dev-dependencies]
env_logger = "0.11"

[target.'cfg(windows)'.dependencies.windows]
optional = true
version = "0.61"
features = [
  "System",
  "Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_HiDpi",
]
