style_edition = "2021"
unstable_features = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_bodies = false # or skip_macro_invocations = [...]
#format_strings = true
#wrap_comments = true
#newline_style = "Unix"

imports_granularity = "One"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"

#condense_wildcard_suffixes = true
match_block_trailing_comma = true
match_arm_leading_pipes = "Preserve"
overflow_delimited_expr = true
#reorder_impl_items = true
trailing_semicolon = false
use_field_init_shorthand = true
