name: Notify about latest release

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get tag message
        id: tag_message
        run: ./ci/get-tag-description.sh
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: ${{ steps.tag_message.outputs.TAG_SUBJECT }}
          embed-description: ${{ steps.tag_message.outputs.TAG_BODY }}
          embed-url: ${{ steps.tag_message.outputs.TAG_URL }}
